import mongoose from "mongoose";
const commentSchema=new mongoose.Schema({
    user:{type:mongoose.Schema.Types.ObjectId,ref:"User",required:true},
    reel:{type:mongoose.Schema.Types.ObjectId,ref:"Reel",required:true},
    comment:{type:String,maxLength:500},
    likes:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"Like"
        }
    ],
    isPinned:{
        type:Boolean,
        default:false
    },
    isLikedByAuthor:{
        type:Boolean,
        default:false
    },
    timestamp:{
        type:Date,
        default:Date.now
    },
    hasGif:{
        type:Boolean,
        default:false
    },
    gifUrl:{
        type:String
    },
    mentionedUsers:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"User"
        }
    ],
    replies:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"Reply"
        }
    ],
})
commentSchema.index({reel:1});
commentSchema.index({user:1});
commentSchema.index({likes:1});
commentSchema.index({mentionedUsers:1});
commentSchema.index({replies:1});
export const  Comment=mongoose.model("Comment",commentSchema);
